name: Deploy to XServer

on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to XServer via rsync
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.XSERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.XSERVER_HOST }}
        REMOTE_USER: ${{ secrets.XSERVER_USER }}
        REMOTE_PORT: 10022 # エックスサーバーのSSHポート番号
        SOURCE: "./" # リポジトリの全ファイルを転送
        TARGET: ${{ secrets.XSERVER_DOMAIN_PATH }}
        ARGS: "-rlgoDvz --delete --exclude='.git*' --exclude='.github*'"
